---
title: "[ISL]CH3_Regression"
author: "Philip oh"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 1. 마케팅 플랜
기술적인 내용은 나중에 추가하겠지만, 3장의 핵심 내용은 '마케팅 플랜'이라고 생각한다. 데이터셋을 보고 어떤 질문들을 던질 있는지, 그리고 그 추상적인 질문들을 어떻게 구체화하고 어떻게 풀어나가는지가 중요하다. 3장의 시작부분에서 `Advertising` 데이터셋을 보고 7가지 질문을 던진다. 그리고 3장 마지막 부분에서 배운 내용을 통해 그 7가지 질문에 어떻게 답할 수 있는지가 나온다. 그 내용은 아래와 같다.

### 1.1 광고 예산과 판매 사이에 상관관계가 있는가?
- 이 질문에 대한 답은 TV, radio, newspaper에 따른 sales의 다중회귀모델을 적합하고 귀무가설을 검정함으로써 얻을 수 있다.
- F통계량은 귀무가설을 기각해야 하는지 결정하는 데 사용될 수 있다.
- 3개의 예측변수를 모두 포함한 다중회귀에서 F통계량에 대응하는 P값은 매우 낮다. 이것은 광고와 판매량 사이에 상관관계가 존재한다는 명백한 증거가 된다.
- 하지만, 광고와 판매량 사이에 상관관계가 있다는 것에서 끝낼 수는 없다. 우리는 이 사실을 통해 몇 가지 질문을 더 던질 수 있다.

### 1.2 광고예산과 판매 사이에 얼마나 강한 상관관계가 있는가?
- 광고예산과 판매 사이에 상관관계가 있다면, 얼마나 강한 상관관계가 있는지도 당연히 궁금해질 것이다.
- 주어진 어떤 광고 예산에 대해 높은 수준의 정확도로 판매를 예측할 수 있다면, 강한 상관관계가 있는 것이다.
- 만약, 광고 지출에 근거한 판매 예측이 임의 추측보다 조금 더 나은 정도라면, 상관관계가 약한 것이라 할 수 있다.
- 모델의 정확도를 나타내는 측도에는 두 가지가 있다. 첫째, RSE는 모회귀선으로부터 반응변수의 표준편차를 추정한다. 둘째, R Square 통계량은 설명변수들에 의해 설명되는 반응변수의 변동을 의미한다.

### 1.3 어느 매체가 기여하는가?
- 3개의 광고매체가 모두 sales에 기여할 수도 있고, 그 중 일부만 기여할 수도 있다. 이 질문에 답하기 위해 각 매체의 효과를 분리해내는 방법을 찾아야 한다.
- TV와 radio에 대한 P값은 낮지만, 신문에 대한 P값은 높다. 즉, TV와 radio만이 sales와 상관관계가 있다는 것을 의미한다.

### 1.4 판매에 대한 각 매체의 효과는 얼마나 되는가?
- TV와 radio에 대한 신뢰구간은 좁고 0과 멀리 떨어져 있다. 이것은 이 매체들이 sales와 관련되어 있다는 증거이다. 그러나 neswpaper에 대한 신뢰구간은 0을 포함하는데, 이것은 주어진 TV와 radio 값에 대해 newspaper 변수는 통계적으로 유의하지 않다는 것을 의미한다.

### 1.5 미래의 판매량에 대해 얼마나 정확하게 예측할 수 있는가?
- 이 추정치와 연관된 정확도는 예측하고자 하는 것이 개별 반응변수 값인지 또는 평균 반응변수 값인지에 따라 다르다.
- 개별 반응변수 값을 예측하고자 한다면 예측구간을 사용하고, 평균 반응변수 값을 예측하고자 한다면 신뢰구간을 사용한다.
- 예측구간은 축소불가능한 오차(irreducible error)와 관련된 불확실성을 포함하기 때문에 항상 신뢰구간보다 더 넓다.

### 1.6 상관관계가 선형적인가?
- 만약 여러 광고의 지출과 판매의 상관관계가 대략 선형적이라면, 선형회귀는 적합한 도구이다. 이 선형회귀를 적용할 수 있는지 확인하기 위해 선형성을 확인한다.
- 잔차 그래프를 통해 선형석을 확인할 수 있다. 만약 상관관계가 선형적이라면 잔차 그래프에 패턴이 없어야 한다.
- 하지만, 만약 비선형적이라고 하더라도 선형회귀를 적용하기 위해 설명변수 또는 반응변수를 변형할 수도 있다.

### 1.7 광고 매체 사이에 시너지가 있는가?
- 하나의 매체에 10만 달러를 사용하는 것보다 5만 달러씩 나눠서 두 개의 매체에 광고하는 것이 더 효과적일 수 있다.
- 상호작용 항과 연관된 p값이 작으면 이러한 설명변수간에 상관관계가 존재한다는 것을 의미한다.